/* export.js */
const Export = (() => {
  function _esc(s){ return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }

  function expPDF() {
    const last = Results.getLast();
    if (!last) { Toast.show('Nothing to export yet.','err'); return; }
    const { r, lang } = last;
    const sc = r.score>=80?'#059669':r.score>=60?'#d97706':'#dc2626';
    const date = new Date().toLocaleDateString('en-IN',{dateStyle:'long'});
    const mkHtml = r.mistakes&&r.mistakes.length
      ? r.mistakes.map(m=>`<div style="border-left:3px solid #ef4444;padding:8px 14px;background:#fef2f2;border-radius:0 6px 6px 0;margin:8px 0"><strong style="color:#ef4444">${_esc(m.title)}</strong><p style="margin:4px 0 0;color:#374151">${_esc(m.body)}</p></div>`).join('')
      : '<p style="color:#059669">✅ No major mistakes found!</p>';
    const qHtml = r.interview_questions.map((q,i)=>`<div style="background:#eff6ff;padding:9px 14px;border-radius:6px;margin:6px 0"><strong style="color:#1d4ed8">Q${i+1}.</strong> ${_esc(q)}</div>`).join('');
    const rmHtml = r.roadmap.map((s,i)=>`<div style="display:flex;gap:12px;padding:10px;background:#f0fdf4;border-radius:6px;margin:6px 0"><div style="width:26px;height:26px;background:#065f46;color:white;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:11px;flex-shrink:0">${i+1}</div><div><strong>${_esc(s.title)}</strong><p style="margin:3px 0 0;color:#374151;font-size:13px">${_esc(s.desc)}</p></div></div>`).join('');
    const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Code Saathi Report</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:Arial,sans-serif;color:#1a1a1a;padding:40px;max-width:860px;margin:auto;line-height:1.6}h1{color:#065f46;font-size:28px;margin-bottom:4px}h2{color:#065f46;border-bottom:2px solid #d1fae5;padding-bottom:6px;margin:24px 0 12px;font-size:18px}.meta{color:#6b7280;font-size:13px;margin-bottom:20px}.score-box{background:#f0fdf4;border:2px solid #d1fae5;border-radius:12px;padding:20px;display:flex;align-items:center;gap:20px;margin-bottom:24px}.score-num{font-size:56px;font-weight:700;color:${sc};font-family:monospace;line-height:1}pre{background:#f8fafc;border:1px solid #e2e8f0;padding:16px;border-radius:8px;overflow-x:auto;font-size:13px;line-height:1.7;margin:10px 0}.cx{display:inline-flex;align-items:center;gap:5px;padding:4px 12px;border-radius:20px;font-size:13px;font-weight:500;margin:3px}@media print{body{padding:20px}}</style>
</head><body>
<h1>Code Saathi Review Report</h1>
<div class="meta">Language: <strong>${lang}</strong> | Generated: ${date}</div>
<div class="score-box">
  <div class="score-num">${r.score}</div>
  <div><div style="font-size:20px;font-weight:600;margin-bottom:4px">${r.score_label}</div><div style="color:#374151">${_esc(r.summary)}</div></div>
</div>
<h2>⏱ Complexity</h2>
<span class="cx" style="background:#f5f3ff;color:#5b21b6">Time: ${_esc(r.complexity.time)}</span>
<span class="cx" style="background:#eff6ff;color:#1d4ed8">Space: ${_esc(r.complexity.space)}</span>
<p style="margin-top:10px">${_esc(r.complexity.explanation)}</p>
<h2>🐛 Mistakes</h2>${mkHtml}
<h2>🚀 Optimized Code</h2><pre>${_esc(r.optimized_code)}</pre><p>${_esc(r.optimization_notes)}</p>
<h2>❓ Interview Questions</h2>${qHtml}
<h2>🗺️ Learning Roadmap</h2>${rmHtml}
<div style="margin-top:40px;padding-top:14px;border-top:1px solid #e2e8f0;font-size:11px;color:#9ca3af;text-align:center">Generated by Code Saathi — AI Learning Code Reviewer | BTech Final Year Project</div>
<script>window.onload=function(){window.print()}<\/script>
</body></html>`;
    const w=window.open('','_blank');
    if(!w){Toast.show('Allow popups for PDF export.','err');return;}
    w.document.write(html); w.document.close();
  }

  function cpyReport() {
    const last=Results.getLast();
    if(!last){Toast.show('Nothing to copy.','err');return;}
    const {r,lang}=last;
    const txt=[
      `CODE SAATHI REPORT\nLanguage: ${lang} | Score: ${r.score}/100 (${r.score_label})`,
      r.summary,'',
      `COMPLEXITY\nTime: ${r.complexity.time} | Space: ${r.complexity.space}\n${r.complexity.explanation}`,'',
      `MISTAKES (${r.mistakes.length})`,
      ...r.mistakes.map((m,i)=>`${i+1}. ${m.title}\n   ${m.body}`),'',
      'OPTIMIZED CODE\n'+r.optimized_code,'',r.optimization_notes,'',
      'INTERVIEW QUESTIONS',
      ...r.interview_questions.map((q,i)=>`Q${i+1}. ${q}`),'',
      'LEARNING ROADMAP',
      ...r.roadmap.map((s,i)=>`${i+1}. ${s.title}\n   ${s.desc}`)
    ].join('\n');
    navigator.clipboard.writeText(txt)
      .then(()=>Toast.show('Copied to clipboard!','ok'))
      .catch(()=>Toast.show('Copy failed.','err'));
  }

  function shareRep() {
    const last=Results.getLast();
    if(!last) return;
    const {r,lang}=last;
    const txt=`I scored ${r.score}/100 on Code Saathi for my ${lang} code! 🚀\n${r.summary}`;
    if(navigator.share){ navigator.share({title:'Code Saathi Review',text:txt}).catch(()=>{}); }
    else { navigator.clipboard.writeText(txt).then(()=>Toast.show('Share text copied!','ok')).catch(()=>{}); }
  }

  return { expPDF, cpyReport, shareRep };
})();

function expPDF()    { Export.expPDF(); }
function cpyReport() { Export.cpyReport(); }
function shareRep()  { Export.shareRep(); }
